# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82eeecab6aa419ab2817efe504a040034eac2ef6d945c9219ee1969f995c7ba9fd392ef17333c673c2dd1da513a5529626eccc757cec83b59d9aa8d5db48fb62

test:
  secret_key_base: f43974945d6e887ab5e27c14b31e55118e3d225d1dfce8e629e8f488cfe1c547876bb019a47578bdfb18890fe1cffe1e82206143987fbf4d962e315fcb454905

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
